services:
  postgres:
    image: postgres:17.2
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: zbelard
    ports:
      - "5432:5432"
    volumes:
      - zbelard_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.2
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - zbelard_redis_data:/data

volumes:
  zbelard_pg_data:
    driver: local
  zbelard_redis_data:
    driver: local
